ALTER TABLE "Tenant"
ADD COLUMN IF NOT EXISTS "locationText" VARCHAR(240),
ADD COLUMN IF NOT EXISTS "currencyCode" CHAR(3) NOT NULL DEFAULT 'PEN',
ADD COLUMN IF NOT EXISTS "referenceSchedule" VARCHAR(160);
